import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800"], variable: "--font-inter" });
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"], weight:["400", "500", "600", "700", "800"], variable: "--font-jakarta" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jakarta.variable}`}>
      <body className="bg-[#000000]">
        <div className="relative -z-10">
          <div className=" absolute w-[725px] h-56 rounded-full left-0 right-0 -top-56 mx-auto bg-amber-400 shadow-[0px_-160px_400px_200px_#D0A70459]"></div>{" "}
        </div>

        <Navbar
          navlist={["Dashboard", "Camera", "Scenes", "Incidents", "Users"]}
        />
        <hr className="border-gray-700" />
        <main className="mx-6">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
